//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Configuration")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false, column_type = "Text")]
    pub id: String,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(column_type = "JsonBinary")]
    pub values: Json,
    #[sea_orm(column_type = "Text")]
    pub hash: String,
    #[sea_orm(column_name = "chainId")]
    pub chain_id: i32,
    #[sea_orm(column_name = "baseTokenAddress", column_type = "Text")]
    pub base_token_address: String,
    #[sea_orm(column_name = "quoteTokenAddress", column_type = "Text")]
    pub quote_token_address: String,
    #[sea_orm(column_name = "baseTokenSymbol", column_type = "Text")]
    pub base_token_symbol: String,
    #[sea_orm(column_name = "quoteTokenSymbol", column_type = "Text")]
    pub quote_token_symbol: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::instance::Entity")]
    Instance,
}

impl Related<super::instance::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Instance.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
