//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Instance")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(column_type = "JsonBinary")]
    pub config: Json,
    #[sea_orm(column_name = "configurationId")]
    pub configuration_id: Option<i32>,
    #[sea_orm(column_name = "startedAt")]
    pub started_at: DateTime,
    #[sea_orm(column_name = "endedAt")]
    pub ended_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::configuration::Entity",
        from = "Column::ConfigurationId",
        to = "super::configuration::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Configuration,
    #[sea_orm(has_many = "super::price::Entity")]
    Price,
    #[sea_orm(has_many = "super::trade::Entity")]
    Trade,
}

impl Related<super::configuration::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Configuration.def()
    }
}

impl Related<super::price::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Price.def()
    }
}

impl Related<super::trade::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Trade.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
