/// =============================================================================
/// Database Entity Models Module
/// =============================================================================
///
/// @description: SeaORM entity models for database operations. This module contains
/// the generated database entities for configuration, instances, prices, and trades
/// used for persistent storage and data management.
/// @generated: Generated by sea-orm-codegen 1.1.12
/// =============================================================================
pub mod prelude;

pub mod configuration;
pub mod instance;
pub mod price;
pub mod trade;
