//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

pub use super::bot::Entity as Bot;
pub use super::log::Entity as Log;
pub use super::price::Entity as Price;
pub use super::trade::Entity as Trade;
