//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.12

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Trade")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_name = "createdAt")]
    pub created_at: DateTime,
    #[sea_orm(column_name = "updatedAt")]
    pub updated_at: DateTime,
    #[sea_orm(column_name = "deletedAt")]
    pub deleted_at: Option<DateTime>,
    #[sea_orm(column_name = "botId")]
    pub bot_id: i32,
    #[sea_orm(column_name = "logId")]
    pub log_id: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub value: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(belongs_to = "super::bot::Entity", from = "Column::BotId", to = "super::bot::Column::Id", on_update = "Cascade", on_delete = "Restrict")]
    Bot,
    #[sea_orm(belongs_to = "super::log::Entity", from = "Column::LogId", to = "super::log::Column::Id", on_update = "Cascade", on_delete = "Restrict")]
    Log,
}

impl Related<super::bot::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Bot.def()
    }
}

impl Related<super::log::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Log.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
